const fs = require('fs');

// Attempt to load .env specifically for local manual runs
// Docker/Railway usually inject environment variables natively, making this redundant in prod.
const env = process.env.ENV || 'dev';
const envFile = process.env.ENV_FILE || `.env.${env}`;

try {
    require('dotenv').config({ path: envFile });
} catch (error) {
    // Silent catch. If dotenv doesn't exist, we just rely on process.env natively.
}

const authApi = process.env.AUTH_API || 'http://localhost:3000';
const userApi = process.env.USER_API || 'http://localhost:3001';

const content = `// Auto-generated by generate-env.js on startup
window.ENV = {
  AUTH_API: '${authApi}',
  USER_API: '${userApi}'
};
`;

fs.writeFileSync('./js/env.js', content);
console.log('Environment configuration injected into js/env.js successfully.');
console.log(`AUTH_API: ${authApi}`);
console.log(`USER_API: ${userApi}`);
